# Generated by Django 6.0.3 on 2026-03-23 23:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1)),
                ('codigo', models.CharField(help_text='Ej: H0249 o M1223', max_length=10, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para dar de BAJA al socio')),
                ('plan_semanal', models.IntegerField(default=3, help_text='Cantidad de días por semana contratados (2, 3, 4, 5)')),
                ('cuota_pagada', models.BooleanField(default=False, verbose_name='¿Cuota Pagada este Mes?')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha en que vence la cuota', null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI')),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.CharField(blank=True, max_length=25, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=25, null=True, verbose_name='Celular de Emergencia')),
                ('fecha_inicio_rutina', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=15)),
                ('tipo', models.CharField(choices=[('AEROBICO', '🏃\u200d♂️ Aeróbico'), ('ZONA_MEDIA', '🧘 Zona Media'), ('FUERZA', '💪 Fuerza')], default='FUERZA', max_length=20)),
                ('series', models.IntegerField(default=1)),
                ('repeticiones', models.CharField(max_length=50)),
                ('peso_sugerido', models.FloatField(blank=True, null=True)),
                ('timmer', models.CharField(blank=True, help_text='Ej: P1, P2, P3 o P4', max_length=10, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('ultima_vez_hecho', models.DateTimeField(blank=True, null=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='alumnos.alumno')),
            ],
            options={
                'ordering': ['tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gym', models.CharField(default='Aquiles Gym', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entrenadores',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_alumnos', to='alumnos.entrenador'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_entrada', models.TimeField(auto_now_add=True)),
                ('porcentaje_completado', models.FloatField(default=0.0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.alumno')),
            ],
            options={
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('alumno', 'fecha')},
            },
        ),
    ]
