# Generated by Django 6.0.3 on 2026-03-17 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='presente',
        ),
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarcar para dar de BAJA al socio'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='codigo',
            field=models.CharField(default='TEMPORAL', help_text='Ej: H0249 o M1223', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='alumno',
            name='plan_semanal',
            field=models.IntegerField(default=3, help_text='Cantidad de días por semana contratados (2, 3, 4, 5)'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='porcentaje_completado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.alumno'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='dia_semana',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=15),
        ),
    ]
