# Generated by Django 6.0.3 on 2026-03-18 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_asistencia_presente_alumno_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_inicio_rutina',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
