# Generated by Django 6.0.3 on 2026-04-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_asistencia_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='cuota_pagada',
        ),
        migrations.AddField(
            model_name='alumno',
            name='ultimo_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Último Pago'),
        ),
    ]
