# Generated by Django 6.0.3 on 2026-03-07 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_rutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.rutina')),
            ],
        ),
    ]
