# Generated by Django 6.0.3 on 2026-03-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_ejercicio_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha en que vence la cuota', null=True),
        ),
    ]
