# Generated by Django 6.0.3 on 2026-03-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='tiempo',
            field=models.IntegerField(blank=True, help_text='Minutos (para aeróbico)', null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('aerobico', 'Aeróbico'), ('abdominal', 'Abdominal')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='repeticiones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='series',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
