# Generated by Django 6.0.3 on 2026-03-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejercicio',
            options={'ordering': ['tipo', 'id']},
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('AEROBICO', '🏃\u200d♂️ Aeróbico'), ('ZONA_MEDIA', '🧘 Zona Media'), ('FUERZA', '💪 Fuerza')], default='FUERZA', max_length=20),
        ),
    ]
