# Generated by Django 6.0.3 on 2026-03-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alter_ejercicio_options_ejercicio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='celular',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Celular de Emergencia'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
