# Generated by Django 6.0.3 on 2026-03-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumno_user_alter_alumno_fecha_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='dia',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
