# Generated by Django 6.0.3 on 2026-03-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alumno_celular_alumno_contacto_emergencia_alumno_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='timmer',
            field=models.CharField(blank=True, help_text='Ej: P1, P2, P3 o P4', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='series',
            field=models.IntegerField(default=1),
        ),
    ]
