# Generated by Django 6.0.3 on 2026-03-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0007_ejercicio_timmer_alter_ejercicio_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cuota_pagada',
            field=models.BooleanField(default=False, verbose_name='¿Cuota Pagada este Mes?'),
        ),
    ]
