# Generated by Django 6.0.3 on 2026-03-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_alumno_cuota_pagada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'verbose_name_plural': 'Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='entrenador',
            options={'verbose_name_plural': 'Entrenadores'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_alumnos', to='alumnos.entrenador'),
        ),
    ]
