# Generated by Django 6.0.3 on 2026-03-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_alter_asistencia_options_alter_entrenador_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='timmer',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='timer',
            field=models.CharField(blank=True, help_text='Ej: 12 MIN, 40 SEG, etc.', max_length=15, null=True),
        ),
    ]
